# Generated by Django 4.2.3 on 2023-07-25 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Profile', models.ImageField(upload_to='about_me/profile/%Y/%m/%d')),
                ('Use', models.CharField(choices=[('PT', 'POST'), ('CO', 'CONSUMER')], default='PT', max_length=2)),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
