# Generated by Django 4.2.3 on 2023-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_alter_consum_author'),
        ('account', '0003_usermodel'),
        ('post', '0003_alter_performancepost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
