# Generated by Django 4.2.3 on 2023-08-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usermodel_managers_alter_usermodel_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='Type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(upload_to='media/profile'),
        ),
    ]
