# Generated by Django 4.2.3 on 2023-07-31 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('intro', models.TextField()),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
