# Generated by Django 4.2.3 on 2023-08-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_performancepost_call_performancepost_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancepost',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performancepost',
            name='deadline',
            field=models.CharField(max_length=50),
        ),
    ]
