# Generated by Django 4.2.3 on 2023-08-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_performancepost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancepost',
            name='info',
        ),
        migrations.AddField(
            model_name='performancepost',
            name='agency',
            field=models.CharField(default='기관명', max_length=50),
        ),
    ]
