# Generated by Django 4.2.3 on 2023-08-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_performancepost_info_performancepost_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancepost',
            old_name='intro',
            new_name='info',
        ),
    ]
