# Generated by Django 4.2.3 on 2023-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_info', models.TextField()),
                ('post_type', models.CharField(max_length=50)),
                ('post_deadline', models.DateTimeField()),
                ('post_date', models.DateTimeField()),
                ('post_location', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='venue_images/')),
                ('post_intro', models.TextField()),
            ],
        ),
    ]
