# Generated by Django 4.2.3 on 2023-07-31 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=17)),
                ('education', models.CharField(max_length=254)),
                ('career', models.CharField(max_length=254)),
                ('award', models.CharField(max_length=254)),
                ('introduce', models.CharField(max_length=254)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consum_user', to='account.user')),
            ],
        ),
    ]
