# Generated by Django 4.2.3 on 2023-07-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumUser',
            new_name='Consum',
        ),
    ]
