# Generated by Django 4.2.3 on 2023-08-03 05:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0004_consum_call_consum_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consum',
            new_name='Resume',
        ),
    ]
