# Generated by Django 4.2.3 on 2023-07-25 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.PositiveIntegerField(help_text='User Age')),
                ('Education', models.CharField(max_length=254)),
                ('Career', models.CharField(max_length=254)),
                ('Award', models.CharField(max_length=254)),
                ('Introduce', models.CharField(max_length=254)),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
