# Generated by Django 4.2.3 on 2023-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='', upload_to='media/profile/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.EmailField(default=1, max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='이름', max_length=100, unique=True, verbose_name='name'),
        ),
    ]
