# Generated by Django 4.2.3 on 2023-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_email_remove_user_id_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
