# Generated by Django 4.2.3 on 2023-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='name'),
        ),
    ]
