# Generated by Django 4.2.3 on 2023-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('PT', 'POST'), ('CO', 'CONSUMER')], default='PT', max_length=2),
        ),
    ]
