# Generated by Django 4.2.3 on 2023-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_created_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(upload_to='about_me/profile/%Y/%m/%d'),
        ),
    ]
