# Generated by Django 4.2.3 on 2023-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='media/profile/default.jpg', upload_to='media/profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email'),
        ),
    ]
